---
- name: Install jellyfin
  hosts: test
  become: true
#  vars_prompt:
#    - name: "username"
#      prompt: "Enter SMB auth. username."
#      private: yes
#    - name: "password"
#      prompt: "Enter SMB auth. password."
#      private: yes
  tasks:
    - name: cifs-utils install
      ansible.builtin.apt:
        name: cifs-utils

    - name: Posix mounting
      mount:
        src: //bt-nas/media
        path: /home/bt/mnt/media
        opts: "rw,credentials=/home/bt/.cred"
        state: mounted
        fstype: cifs
    
    - name: Install jf
      ansible.builtin.shell:
      cmd: "diff <( curl -s https://repo.jellyfin.org/install-debuntu.sh -o install-debuntu.sh; sha256sum install-debuntu.sh ) <( curl -s https://repo.jellyfin.org/install-debuntu.sh.sha256sum )"