---
- name: Install jellyfin
  hosts: test
  become: true
#  vars_prompt:
#    - name: "username"
#      prompt: "Enter SMB auth. username."
#      private: yes
#    - name: "password"
#      prompt: "Enter SMB auth. password."
#      private: yes
  tasks:
    - name: cifs-utils install
      ansible.builtin.apt:
        name: cifs-utils
    - name: Posix mounting
      mount:
        src: //192.168.86.40/media
        path: /home/bt/mnt/media
        opts: "rw,credentials=/home/bt/.cred"
        state: mounted
        fstype: cifs